import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
	title: "MahmoudBA Website",
	description: "Generated by Next + Sanity",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
}
