import { getPages } from "@/sanity/sanity-utils";
import "../globals.css";
import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
	title: "MahmoudBA Website",
	description: "Generated by Next + Sanity",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const pages = await getPages();
	return (
		<html lang="en">
			<body className="max-w-3xl mx-auto py-10">
				<header className="flex items-center justify-between">
					<Link
						href="/"
						className="bg-gradient-to-r from-green-400  to-yellow-400 bg-clip-text text-transparent text-lg font-bold"
					>
						MahmoudBA
					</Link>
					<div className="flex items-center gap-2 text-sm text-gray-600">
						{pages.map((page) => (
							<Link
								className="hover:text-green-500 hover:underline font-bold transition"
								key={page._id}
								href={`/${page.slug}`}
							>
								{page.title}
							</Link>
						))}
					</div>
				</header>
				<main>{children}</main>
			</body>
		</html>
	);
}
